# lecture_1

In [1]:
import numpy as np

In [2]:
mylist= [1,2,3,4] 

In [5]:
myarr = np.array(mylist)

In [6]:
myarr

array([1, 2, 3, 4])

In [7]:
type(myarr)

numpy.ndarray

In [16]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [17]:
numpymatrix = np.array(mymatrix)

In [18]:
numpymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [20]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [28]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.random.rand(3,4)   #return np array of given size having
                      #uniformly distributed values from [0,1)

array([[0.56500459, 0.70695132, 0.42267038, 0.8241224 ],
       [0.16386117, 0.30841169, 0.81492593, 0.94759641],
       [0.4348913 , 0.905776  , 0.38033717, 0.75455163]])

In [31]:
np.random.randn(2,5)   #return np array of given size having
                       #normally distributed values

array([[ 0.01827918, -0.75787145, -0.41663297, -0.43929757, -0.23481152],
       [ 0.45546093,  1.29430812, -0.77191886,  0.17425729,  1.3519794 ]])

In [39]:
"""
Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
"""
np.random.randint(1,100,(4,5))

array([[26, 27, 72, 87, 43],
       [65, 52,  1, 57, 57],
       [55,  6, 88,  9,  1],
       [59, 63, 11,  7, 28]])

In [49]:
np.random.rand(3,4)

array([[0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195, 0.6976312 , 0.06022547],
       [0.66676672, 0.67063787, 0.21038256, 0.1289263 ]])

In [40]:
np.random.seed(42)
np.random.rand(3,4)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

In [44]:
np.random.seed(42)
np.random.rand(3,4)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

In [45]:
np.random.seed(0)
np.random.rand(3,4)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])

In [46]:
np.random.seed(0)
np.random.rand(3,4)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])

In [48]:
np.random.rand(3,4)

array([[0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 , 0.6176355 ]])

In [53]:
arr = np.arange(0,24)

In [55]:
arr.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [58]:
ranarr = np.random.randint(0,101,10)

In [59]:
ranarr

array([ 47,   3,  76, 100,  52,  78,  15,  20,  99,  58])

In [63]:
ranarr.max()

100

In [64]:
ranarr.min()

3

In [67]:
ranarr.argmax()  #returns index of max element from array

3

In [68]:
ranarr.argmin()  #returns index of min element from array

1

In [69]:
ranarr.dtype

dtype('int32')

In [71]:
arr = np.arange(25)

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [73]:
arr.shape

(25,)

In [74]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
arr.shape

(25,)

In [78]:
arr = arr.reshape(5,5)

In [79]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [80]:
arr.shape

(5, 5)

# lecture_2

In [81]:
arr = np.arange(0,11)

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr[8]

8

In [84]:
arr[1:5]

array([1, 2, 3, 4])

In [85]:
arr[:5]

array([0, 1, 2, 3, 4])

In [86]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [87]:
arr[:5] = 100  #broadcasting

In [88]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [99]:
arr = np.arange(0,11)

In [100]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
slice_of_arr = arr[:5]

In [102]:
slice_of_arr[:] = 88

In [103]:
arr     #point to be noted: operation on slice_of_arr reflected on original arr

array([88, 88, 88, 88, 88,  5,  6,  7,  8,  9, 10])

In [104]:
arr_copy = arr.copy()

In [105]:
arr_copy[:] = 100

In [106]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [107]:
arr

array([88, 88, 88, 88, 88,  5,  6,  7,  8,  9, 10])

In [111]:
arr_2d = np.arange(5,46,5).reshape(3,3)

In [112]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [113]:
arr_2d.shape

(3, 3)

In [114]:
arr_2d[0]

array([ 5, 10, 15])

In [115]:
arr_2d[-1]

array([35, 40, 45])

In [116]:
arr_2d[1][1]

25

In [117]:
arr_2d[1,1]

25

In [118]:
arr_2d[0,2]

15

In [119]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [120]:
arr = np.arange(11)

In [121]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [123]:
bool_arr = arr > 4

In [124]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [125]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [126]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [127]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
arr[arr==1]

array([1])

In [129]:
arr[arr<7]

array([0, 1, 2, 3, 4, 5, 6])

# lecture_3

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [6]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
arr/arr    #0/0 can't be done thats why warning is there

C:\Users\THINKPAD\AppData\Local\Temp\ipykernel_1452\2181000911.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr    #0/0 can't be done thats why warning is there


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
1/arr

C:\Users\THINKPAD\AppData\Local\Temp\ipykernel_1452\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [15]:
np.log(arr)

C:\Users\THINKPAD\AppData\Local\Temp\ipykernel_1452\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [16]:
np.sum(arr)

45

In [17]:
np.mean(arr)

4.5

In [19]:
np.var(arr)

8.25

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr_2d = np.arange(0,25).reshape(5,5)

In [22]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
arr_2d.sum()

300

In [24]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [25]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])